#!/bin/bash

image_frieren="frieren.jpeg"
image_anime_boy="anime_boy_chill.jpg"
image_night_sky="wp2150006-anime-city-wallpapers.png"

image_path="$BASH_CONFIG/source/pictures/wallpapers/$image_night_sky"


set_gnome_background() {
    local image_path="$1"

    if [ ! -f "$image_path" ]; then
        echo "File does not exits: file://$image_path"
    fi

    gsettings set org.gnome.desktop.background picture-uri "file://$image_path"
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$image_path"

    if [ $? -eq 0 ]; then
        echo "Successfully set the background image to file://$image_path"
    else 
        echo "$?"
        echo "Failed to set the background image"
    fi
}

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 /path/to/image"
fi

set_gnome_background "$image_path"
