#!/bin/bash
export XDG_CONFIG_HOME="$HOME/.config" 
export CONFIG="$HOME/.my_config"
export BASH_CONFIG="$CONFIG/bash_config"
export ENV="$BASH_CONFIG/.env"
export BASH_PATH="$BASH_CONFIG/bash_path.sh"
export BASH_VARIABLE="$BASH_CONFIG/.bash_variables"
export BASH_ALIAS="$BASH_CONFIG/.bash_aliases"
export GNOME_SETTING="$BASH_CONFIG/gnome_setting"
export GNOME_CONFIG="$GNOME_SETTING/.gnome_config.sh"
export IMAGE_RESOURCE="$HOME/Pictures/resources"
export TEMP_DIR="$HOME/.cache/temp"


export PATH="$BASH_CONFIG/scripts:$PATH"
export PATH="/hom/light/.bash_config/functions/compile/bin:$PATH"
export PATH="/opt/nvim-linux64/bin:$PATH"
export PATH="/opt/nvim-linux-x86_64/bin:$PATH"
export PATH="/home/light/development/flutter/bin:$PATH"
export PATH="/home/light/.bash_config/hancom:$PATH"
export PATH="$SPRING_HOME/bin:$PATH"
export PATH="$HOME/.pub-cache/bin:$PATH"
export PATH="$HOME/.rvm/bin:$PATH"
export PATH="$JAVA_HOME/bin:$PATH"
export PATH="/opt/gradle/gradle-8.13/bin:$PATH"
export PATH="$ANDROID_HOME/cmdline-tools/tools:$ANDROID_HOME/cmdline-tools/tools/bin:$ANDROID_HOME/platform-tools:$PATH"
export PATH="$ANDROID_HOME/emulator:$PATH"

