#!/bin/bash
# export PS1="\n$(__mkps1_box_top)$(__mkps1_debian_chroot)$(__mkps1_exitcode)$(__mkps1_time)$(__mkps1_username)$(__mkps1_arrows) $(__mkps1_workdir)$(__mkps1_git)\n$(__mkps1_box_bottom)$(__mkps1_user_prompt)"
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

BASH_VARIABLE="$HOME/.my_config/bash_config/.bash_variables"

if [ -f $BASH_VARIABLE ]; then
	. $BASH_VARIABLE
else
	echo "bash_variables is missing"
fi


if [ -f ~/.my_config/bash_config/bash_path.sh ]; then
	. ~/.my_config/bash_config/bash_path.sh
fi

if [ -f $BASH_ALIAS ]; then
	. $BASH_ALIAS
else
	echo "bash_aliases is missing"
fi

if [ ! -f $ENV ]; then
	echo "env file is missing, exit code: $?";
else
	. $ENV
fi


if [ ! -f $GNOME_CONFIG ]; then
	echo "gnome_setting is missing"
else
	. $GNOME_CONFIG
fi

if [ ! -f $HOME/.cargo/env ]; then
	echo "cargo/env is missing";
else
	. $HOME/.cargo/env
fi
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
eval "$(starship init bash)"
eval "$(zoxide init bash)"
eval "$(fzf --bash)"
#
# set -o vi
session="workspace"
sub_session="subspace"

# tmux inside tmux 방지
if [ -n "$TMUX" ]; then
    return
fi

# tmux 서버가 이미 살아있는지 확인
if tmux ls >/dev/null 2>&1; then
    # 서버 살아있으면 sub_session으로
    if tmux has-session -t "$sub_session" 2>/dev/null; then
        tmux attach-session -t "$sub_session"
    else
        tmux new-session -s "$sub_session"
    fi
else
    # 최초 터미널은 workspace로
    if tmux has-session -t "$session" 2>/dev/null; then
        tmux attach-session -t "$session"
    else
        tmux new-session -s "$session"
    fi
fi

fzf_insert_path() {
  local dir
  dir=$(find ../../.. -maxdepth 3 -type d | fzf) || return
  # Insert directory path at cursor
  READLINE_LINE="${READLINE_LINE:0:READLINE_POINT}$dir${READLINE_LINE:READLINE_POINT}"
  READLINE_POINT=$(( READLINE_POINT + ${#dir} ))
}

bind -x '"\C-g": fzf_insert_path'
