#!/bin/bash
# export PS1="\n$(__mkps1_box_top)$(__mkps1_debian_chroot)$(__mkps1_exitcode)$(__mkps1_time)$(__mkps1_username)$(__mkps1_arrows) $(__mkps1_workdir)$(__mkps1_git)\n$(__mkps1_box_bottom)$(__mkps1_user_prompt)"
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

if [ -f $BASH_VARIABLE ]; then
	. $BASH_VARIABLE
else
	echo "bash_variables is missing"
fi

if [ -f ~/.my_config/bash_config/bash_path.sh ]; then
	. ~/.my_config/bash_config/bash_path.sh
fi

if [ -f $BASH_ALIAS ]; then
	. $BASH_ALIAS
else
	echo "bash_aliases is missing"
fi

if [ ! -f $ENV ]; then
	echo "env file is missing, exit code: $?";
else
	. $ENV
fi


if [ ! -f $GNOME_CONFIG ]; then
	echo "gnome_setting is missing"
else
	. $GNOME_CONFIG
fi

if [ ! -f $HOME/.cargo/env ]; then
	echo "cargo/env is missing";
else
	. $HOME/.cargo/env
fi
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
eval "$(starship init bash)"
eval "$(zoxide init bash)"
eval "$(fzf --bash)"
#
# set -o vi
session="workspace"
sub_session="sub"
# blank ses
# ses blank
# ses tm
# tm ses
# if [ -z "$TMUX" ]; then
# 	if tmux has-session -t $session 2>/dev/null && [ $? == 0 ]; then
# 		tmux attach-session -t $session
# 	else
# 		tmux new -s $session
# 	fi
# fi

if [ -z "$TMUX" ]; then
	if tmux has-session -t $session 2>/dev/null && [ $? == 0 ]; then
		# tmux attach-session -t $session
		tmux new -s $sub_session
	else
		tmux new -s $session
	fi
fi

