#!bin/bash

# export PS1="\n$(__mkps1_box_top)$(__mkps1_debian_chroot)$(__mkps1_exitcode)$(__mkps1_time)$(__mkps1_username)$(__mkps1_arrows) $(__mkps1_workdir)$(__mkps1_git)\n$(__mkps1_box_bottom)$(__mkps1_user_prompt)"
. $HOME/.my_config/bash_config/.bash_variables
. $BASH_CONFIG/.env

export PS1="\e[0;34m\u@\h \w> \e[m"
eval "$(starship init bash)"
export PATH="$PATH:/home/light/development/flutter/bin"
export PATH="$PATH:/home/light/.bash_config/hancom"
export JAVA_HOME=/usr/lib/jvm/jdk-23.0.1-oracle-x64
export SPRING_HOME=/opt/spring-3.4.0
export PATH="$PATH:/$SPRING_HOME/bin"
export PATH="$PATH":"$HOME/.pub-cache/bin"

if [ -f $BASH_CONFIG/.bash_aliases ]; then
	echo "sourced bash_aliases"
	. $BASH_CONFIG/.bash_aliases
fi

if [ -f $BASH_CONFIG/.bash_variables ]; then
	echo "sourced bash_variables"
	. $BASH_CONFIG/.bash_variables
fi

if [ -f $BASH_CONFIG/gnome_setting/.gnome_config ]; then
	echo "sourced gnome_setting"
	. $BASH_CONFIG/gnome_setting/.gnome_config
fi


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
. "$HOME/.cargo/env"

 export PATH="~/.local/bin:$PATH"
export PATH="~/development/flutter/bin:$PATH"


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/light/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/light/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/light/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/light/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
