#!/bin/bash

function mk_cd {
    local DIRECTORY=$1

	mkdir $DIRECTORY

	if [ $? -eq 0 ]; then
		echo "Successfully make $DIRECTORY."
	else 
		echo "Making $DIRECTION FAIL"
		exit 1;
	fi

	cd $DIRECTORY

	if [ $? -eq 0 ]; then
		echo "Successfully move to $DIRECTORY."
	else	
		echo "Failed to move to $DIRECTORY."
	fi
}

mk_cd $1
