SCREENSHOT_PATH=~/Pictures/Screenshots;

SCREENSHOT_PATH="$SCREENSHOT_PATH/$(ls -t $SCREENSHOT_PATH | head -n 1)";
IMAGE_EXTENSION=${SCREENSHOT_PATH##*.};
# input file name default none
DESTINATION_PATH="$1.$IMAGE_EXTENSION"
mv "$SCREENSHOT_PATH" $DESTINATION_PATH
